version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  postgres:
    image: "postgres:9.6"
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${BASE_PATH:-/data}/pgdata:/var/lib/postgresql/data
      - /var/backup/pgsql:/var/backup/pgsql
    env_file:
      - local.env

  rabbitmq:
    image: "rabbitmq:3"
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - local.env

  memcached:
    image: "memcached:alpine"
    restart: unless-stopped
    logging: *default-logging

  awx_web:
    image: "ansible/awx_web:6.1.0"
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - 8051:80
    volumes:
      - "${BASE_PATH:-/data}/SECRET_KEY:/etc/tower/SECRET_KEY"
    hostname: awxweb
    user: root
    env_file:
      - local.env

  awx_task:
    image: "ansible/awx_task:6.1.0"
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - rabbitmq
      - memcached
      - awx_web
      - postgres
    volumes:
      - "${BASE_PATH:-/data}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${BASE_PATH:-/data}/ansible:/data/ansible"
    hostname: awxtask
    user: root
    env_file:
      - local.env