version: '3'
services:
  postgres:
    image: "ultimate1/awx_postgres:latest"
    env_file:
      local.env

  rabbitmq:
    image: "ultimate1/awx_rabbit:latest"
    env_file:
      local.env

  memcached:
    image: "ultimate1/awx_memcached:latest"

  awx_web:
    image: "ultimate1/awx_web_compose:latest"
    links:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    env_file:
      local.env

  awx_task:
    image: "ultimate1/awx_task_compose:latest"
    links:
      - rabbitmq
      - memcached
      - awx_web:awxweb
      - postgres
    hostname: awx
    user: root
    env_file:
      local.env
    volumes:
      -  ~/nginx_install:/var/lib/awx/projects/install