version: '3'
services:
  postgres:
    image: "postgres:9.6"
    env_file:
      local.env

  rabbitmq:
    image: "rabbitmq:3"
    env_file:
      local.env

  memcached:
    image: "memcached:alpine"

  awx_web:
    image: "ultimate1/awx_web_compose:latest"
    #image: "ansible/awx_web:latest"
    links:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "8051:80"
    hostname: awxweb
    user: root
    env_file:
      local.env

  awx_task:
    image: "ultimate1/awx_task_compose:latest"
    #image: "ansible/awx_task:latest"
    links:
      - rabbitmq
      - memcached
      - awx_web:awxweb
      - postgres
    hostname: awx
    user: root
    env_file:
      local.env