---
- hosts: all
  become: true
  become_user: ultimate1
  become_method: sudo
  tasks: 
    - name: try copy java file  
      get_url:
        url: https://github.com/servelat1/nginx_install/raw/main/echoserver.class 
        dest: /tmp/
        force: yes
    - name: Run the java program
      shell: java -cp /tmp/ echoserver &
      async: 10
      poll: 0
    - name: Install nginx
      apt:
       name: nginx
       state: latest