---
- hosts: all
  tasks:
    - name: Run the java program
      shell: java test
    - name: ensure nginx is at the latest version
      apt: name=java state=latest
    - name: start nginx
      service:
          name: java
          state: started
