---
- hosts: all
  tasks:
    - name: try copy java file  
      command: cp https://github.com/servelat1/nginx_install.git/echoserver.class /tmp creates=dest
    - name: Run the java program
      shell: java test
    - name: ensure nginx is at the latest version
      apt: name=java state=latest
    - name: start nginx
      service:
          name: java
          state: started
