---
- name: copy Java and install nginx
  hosts: all
  become: yes
  tasks: 
    - name: try copy java file  
      get_url:
        url: https://github.com/servelat1/nginx_install/raw/main/echoserver.class 
        dest: /tmp/
        force: yes
    - name: Run the java program
      shell: java -cp /tmp/ echoserver &
      async: 10
      poll: 0
    - name: Install nginx
      apt:
       name: nginx
       state: latest